name: Builder APK

on:
  push:
    branches: [ principal, main ]

jobs:
  construire:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libltdl-dev
          pip install --upgrade buildozer Cython==0.29.33
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          cd KWIN-LOTTO
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kwin-lotto-apk
          path: KWIN-LOTTO/bin/*.apk
